using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.Json;
using DuckBot.Data.Models;

namespace DuckBot.Core.Scripts
{
    public static class ScriptTranspiler
    {
        public static string Transpile(ScriptModel script, IDictionary<string, object>? variableOverrides = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by DuckBot Script Builder");
            sb.AppendLine($"// Game: {script.Game}, Script: {script.Name}");
            sb.AppendLine($"// Author: {script.Author}");
            sb.AppendLine();

            if (script.Variables.Count > 0)
            {
                sb.AppendLine("// Variables");
                foreach (var variable in script.Variables)
                {
                    string identifier = SanitizeIdentifier(variable.Key);
                    object? value = variableOverrides != null && variableOverrides.TryGetValue(variable.Key, out var overrideValue)
                        ? overrideValue
                        : variable.Default;
                    sb.Append("const ").Append(identifier).Append(" = ")
                      .Append(JsonSerializer.Serialize(value ?? string.Empty)).AppendLine(";");
                }
                sb.AppendLine();
            }

            foreach (var step in script.Steps)
                AppendStep(sb, step, 0);

            return sb.ToString();
        }

        private static void AppendStep(StringBuilder sb, ScriptStep step, int indent)
        {
            string tabs = new(' ', indent * 2);
            switch (step.Type.ToUpperInvariant())
            {
                case "TAP":
                    sb.AppendLine($"{tabs}adb.tap({step.GetValue("x", 0)},{step.GetValue("y", 0)}); util.sleep({step.GetValue("delay", 500)});");
                    break;
                case "WAIT":
                    sb.AppendLine($"{tabs}util.sleep({step.GetValue("delay", 1000)});");
                    break;
                case "INPUT":
                    sb.AppendLine($"{tabs}adb.inputText({JsonSerializer.Serialize(step.GetValue("text", string.Empty))});");
                    break;
                case "LOG":
                    sb.AppendLine($"{tabs}print({JsonSerializer.Serialize(step.GetValue("message", string.Empty))});");
                    break;
                case "CUSTOM_JS":
                    sb.AppendLine(tabs + step.GetValue("code", string.Empty));
                    break;
                case "IF_IMAGE":
                    AppendIfBlock(sb, step, indent);
                    break;
                case "LOOP":
                    AppendLoop(sb, step, indent);
                    break;
                default:
                    sb.AppendLine($"{tabs}// Unknown step: {step.Type}");
                    break;
            }
        }

        private static void AppendIfBlock(StringBuilder sb, ScriptStep step, int indent)
        {
            string tabs = new(' ', indent * 2);
            string path = step.GetValue("imagePath", string.Empty);
            double confidence = step.GetValue("confidence", 0.9);
            sb.AppendLine($"{tabs}if (cv.find({JsonSerializer.Serialize(path)},{confidence.ToString(System.Globalization.CultureInfo.InvariantCulture)})) {{");

            if (step.ActionIfFound != null)
            {
                foreach (var child in step.ActionIfFound)
                    AppendStep(sb, child, indent + 1);
            }
            else
            {
                sb.AppendLine(new string(' ', (indent + 1) * 2) + "// no actions when image is found");
            }

            if (step.ActionIfNotFound != null && step.ActionIfNotFound.Count > 0)
            {
                sb.AppendLine($"{tabs}}} else {{");
                foreach (var child in step.ActionIfNotFound)
                    AppendStep(sb, child, indent + 1);
            }

            sb.AppendLine($"{tabs}}}");
        }

        private static void AppendLoop(StringBuilder sb, ScriptStep step, int indent)
        {
            string tabs = new(' ', indent * 2);
            int count = step.GetValue("count", 1);
            sb.AppendLine($"{tabs}for (let loopIndex = 0; loopIndex < {count}; loopIndex++) {{");
            if (step.ActionIfFound != null && step.ActionIfFound.Count > 0)
            {
                foreach (var child in step.ActionIfFound)
                    AppendStep(sb, child, indent + 1);
            }
            else
            {
                sb.AppendLine(new string(' ', (indent + 1) * 2) + "// loop body is empty");
            }
            sb.AppendLine($"{tabs}}}");
        }

        private static string SanitizeIdentifier(string key)
        {
            var sb = new StringBuilder();
            if (string.IsNullOrWhiteSpace(key)) return "var";
            if (!char.IsLetter(key[0]) && key[0] != '_') sb.Append('_');
            foreach (var ch in key)
            {
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            }
            return sb.ToString();
        }
    }
}