using System.Text;
using DuckBot.Data.Models;

namespace DuckBot.Core.Scripts
{
    public static class ScriptTranspiler
    {
        // TODO: Add variable injection before transpilation

        public static string Transpile(ScriptModel script)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"// Auto-generated by DuckBot Script Builder");
            sb.AppendLine($"// Game: {script.Game}, Script: {script.Name}");
            sb.AppendLine();

            foreach (var step in script.Steps)
                sb.AppendLine(TranspileStep(step, 0));

            return sb.ToString();
        }

        private static string TranspileStep(ScriptStep step, int indent)
        {
            string tabs = new(' ', indent * 2);
            string line = step.Type switch
            {
                "TAP" => $"{tabs}adb.tap({step.Params["x"]},{step.Params["y"]}); util.sleep({step.Params["delay"]});",
                "WAIT" => $"{tabs}util.sleep({step.Params["delay"]});",
                "INPUT" => $"{tabs}adb.inputText(\"{step.Params["text"]}\");",
                "LOG" => $"{tabs}print(\"{step.Params["message"]}\");",
                "CUSTOM_JS" => $"{tabs}{step.Params["code"]}",
                "IF_IMAGE" => $"{tabs}if (cv.find(\"{step.Params["imagePath"]}\",{step.Params["confidence"]})) {{",
                "END_IF_IMAGE" => $"{tabs}}}",
                _ => $"{tabs}// Unknown step: {step.Type}"
            };

            // TODO: handle nested steps (action_if_found, etc.)
            return line;
        }
    }
}
